# Generated by Django 6.0.6 on 2026-08-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revise', '0002_solved_q_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
            ],
        ),
    ]
